// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBspxeoNYQ-42T9jLg1PEtConVJN8PSeLs',
    appId: '1:392745471062:web:c04eabf82529eeb19b7ff7',
    messagingSenderId: '392745471062',
    projectId: 'albiba-endangerediguanas',
    authDomain: 'albiba-endangerediguanas.firebaseapp.com',
    databaseURL: 'https://albiba-endangerediguanas-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'albiba-endangerediguanas.firebasestorage.app',
    measurementId: 'G-LMFEZTJ3RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3tFF8ItdVcTM3jg83I3VOv6XY6JcAoEk',
    appId: '1:392745471062:android:e3237b8efcce29119b7ff7',
    messagingSenderId: '392745471062',
    projectId: 'albiba-endangerediguanas',
    databaseURL: 'https://albiba-endangerediguanas-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'albiba-endangerediguanas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgabQV0ZAseEujqDzdQVNuMbTYVFu4f8U',
    appId: '1:392745471062:ios:22cec1ecf5fa3fa69b7ff7',
    messagingSenderId: '392745471062',
    projectId: 'albiba-endangerediguanas',
    databaseURL: 'https://albiba-endangerediguanas-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'albiba-endangerediguanas.firebasestorage.app',
    iosBundleId: 'com.example.flutterVistal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgabQV0ZAseEujqDzdQVNuMbTYVFu4f8U',
    appId: '1:392745471062:ios:22cec1ecf5fa3fa69b7ff7',
    messagingSenderId: '392745471062',
    projectId: 'albiba-endangerediguanas',
    databaseURL: 'https://albiba-endangerediguanas-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'albiba-endangerediguanas.firebasestorage.app',
    iosBundleId: 'com.example.flutterVistal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBspxeoNYQ-42T9jLg1PEtConVJN8PSeLs',
    appId: '1:392745471062:web:6ade480ab13ead299b7ff7',
    messagingSenderId: '392745471062',
    projectId: 'albiba-endangerediguanas',
    authDomain: 'albiba-endangerediguanas.firebaseapp.com',
    databaseURL: 'https://albiba-endangerediguanas-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'albiba-endangerediguanas.firebasestorage.app',
    measurementId: 'G-PGVMRS5MLQ',
  );
}
